import React, { useState } from "react";
import { View, StyleSheet, Text, ScrollView, ActivityIndicator, Alert } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Stack } from "expo-router";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { FileText, Download } from "lucide-react-native";

import { colors, spacingX, spacingY, FONTS, fontSizes, dynamicSpacingY } from "../../../../theme/Theme";
import { Button, ScreenHeader } from "../../../../components";
import { useStatsData } from "../../../../hooks/useStatsData";

export default function ReportsScreen() {
  const { stats, loading } = useStatsData();
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    if (!stats) return;
    setIsGenerating(true);
    
    const d = new Date();
    const dateString = `${d.getFullYear()}-${(d.getMonth() + 1).toString().padStart(2, '0')}-${d.getDate().toString().padStart(2, '0')}`;

    // Helper to format numbers safely
    const safeNum = (num: any) => (num !== undefined && num !== null) ? num : 0;
    const safeAvg = (num: any) => (num !== undefined && num !== null) ? num.toFixed(1) : "N/A";

    // Extracting generic stats safely based on typical useStatsData structure
    // Overview
    const totalSessions = safeNum(stats.totalSessions) + safeNum(stats?.breathing?.totalSessions) + safeNum(stats?.drills?.totalSessions);
    const totalMinutes = safeNum(stats.totalMinutes) + safeNum(stats?.breathing?.totalMinutes) + safeNum(stats?.drills?.totalMinutes);
    
    // Detailed stats
    const breathingSessions = safeNum(stats?.breathing?.totalSessions);
    const drillsSessions = safeNum(stats?.drills?.totalSessions);
    const dafSessions = safeNum(stats?.audio?.dafSessions);
    const fafSessions = safeNum(stats?.audio?.fafSessions);

    const htmlContent = `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; margin: 0; padding: 40px; background-color: #f9f9f9; }
            .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #5A67D8; padding-bottom: 20px; }
            .title { font-size: 32px; font-weight: bold; color: #1a202c; margin: 0; }
            .subtitle { font-size: 16px; color: #718096; margin-top: 10px; }
            .section { background: white; padding: 30px; border-radius: 12px; margin-bottom: 30px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
            .section-title { font-size: 20px; font-weight: bold; color: #2d3748; margin-bottom: 20px; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px; }
            .stats-grid { display: flex; flex-wrap: wrap; margin: -10px; }
            .stat-box { flex: 1; min-width: 150px; background: #ebf4ff; margin: 10px; padding: 20px; border-radius: 8px; text-align: center; }
            .stat-value { font-size: 28px; font-weight: bold; color: #5A67D8; }
            .stat-label { font-size: 14px; color: #4a5568; margin-top: 5px; text-transform: uppercase; letter-spacing: 0.5px; }
            .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #a0aec0; }
            ul { list-style-type: none; padding: 0; }
            li { background: #f7fafc; margin-bottom: 10px; padding: 15px; border-radius: 6px; display: flex; justify-content: space-between; font-weight: 500; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1 class="title">Therapy Progress Report</h1>
            <div class="subtitle">Generated on ${dateString}</div>
          </div>
          
          <div class="section">
            <div class="section-title">Overview</div>
            <div class="stats-grid">
              <div class="stat-box">
                <div class="stat-value">${totalSessions}</div>
                <div class="stat-label">Total Sessions</div>
              </div>
              <div class="stat-box">
                <div class="stat-value">${totalMinutes}</div>
                <div class="stat-label">Total Minutes</div>
              </div>
            </div>
          </div>

          <div class="section">
            <div class="section-title">Tool Breakdown</div>
            <ul>
              <li><span>Breathing Exercises</span> <span>${breathingSessions} sessions</span></li>
              <li><span>Speech Drills</span> <span>${drillsSessions} sessions</span></li>
              <li><span>DAF Usage</span> <span>${dafSessions} sessions</span></li>
              <li><span>FAF Usage</span> <span>${fafSessions} sessions</span></li>
            </ul>
          </div>
          
          <div class="footer">
            Report generated by SayThis Therapy App
          </div>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      const isSharingAvailable = await Sharing.isAvailableAsync();
      
      if (isSharingAvailable) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Download Therapy Report',
          UTI: 'com.adobe.pdf'
        });
      } else {
        Alert.alert("Sharing not available", "Cannot share the PDF on this device.");
      }
    } catch (error) {
      console.error("Error generating PDF:", error);
      Alert.alert("Error", "Could not generate the report PDF.");
    } finally {
      setIsGenerating(false);
    }
  };

  if (loading) {
    return (
      <View style={[styles.container, styles.center]}>
        <ActivityIndicator size="large" color={colors.secondary} />
      </View>
    );
  }

  // Calculate generic stats safely
  const totalSessions = stats ? ((stats.totalSessions || 0) + (stats?.breathing?.totalSessions || 0) + (stats?.drills?.totalSessions || 0)) : 0;
  const totalMinutes = stats ? ((stats.totalMinutes || 0) + (stats?.breathing?.totalMinutes || 0) + (stats?.drills?.totalMinutes || 0)) : 0;

  return (
    <SafeAreaView style={styles.container} edges={["top"]}>
      <Stack.Screen options={{ headerShown: false }} />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <ScreenHeader title="Therapy Report" />
        
        <View style={styles.header}>
          <View style={styles.iconContainer}>
            <FileText size={48} color={colors.primary} />
          </View>
          <Text style={styles.title}>Your Therapy Report</Text>
          <Text style={styles.description}>
            Generate and download a comprehensive PDF report of your therapy statistics, progress, and tool usage over time.
          </Text>
        </View>

        <View style={styles.statsPreview}>
          <Text style={styles.previewTitle}>Report Preview</Text>
          
          <View style={styles.statRow}>
            <Text style={styles.statLabel}>Total Sessions</Text>
            <Text style={styles.statValue}>{totalSessions}</Text>
          </View>
          <View style={styles.divider} />
          
          <View style={styles.statRow}>
            <Text style={styles.statLabel}>Total Minutes</Text>
            <Text style={styles.statValue}>{totalMinutes}</Text>
          </View>
        </View>

        <View style={styles.actionContainer}>
          <Button
            title={isGenerating ? "Generating..." : "Download Report (PDF)"}
            onPress={generatePDF}
            variant="primary"
            icon={<Download size={20} color={colors.secondary} />}
            disabled={isGenerating || !stats}
            style={styles.downloadButton}
          />
        </View>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  center: {
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    padding: spacingX.lg,
    paddingBottom: 120,
  },
  header: {
    alignItems: "center",
    marginTop: spacingY.md,
    marginBottom: spacingY.xl,
    paddingHorizontal: spacingX.md,
  },
  iconContainer: {
    width: dynamicSpacingY(12),
    height: dynamicSpacingY(12),
    borderRadius: dynamicSpacingY(6),
    backgroundColor: colors.secondary_20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacingY.md,
  },
  title: {
    fontFamily: FONTS.primaryBold,
    fontSize: fontSizes.xxl,
    color: colors.black,
    marginBottom: spacingY.sm,
    textAlign: "center",
  },
  description: {
    fontFamily: FONTS.primary,
    fontSize: fontSizes.medium,
    color: colors.black_text,
    textAlign: "center",
    lineHeight: fontSizes.medium * 1.5,
  },
  statsPreview: {
    backgroundColor: colors.white,
    borderRadius: spacingY.lg,
    padding: spacingX.lg,
    marginBottom: spacingY.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  previewTitle: {
    fontFamily: FONTS.primaryBold,
    fontSize: fontSizes.large,
    color: colors.black,
    marginBottom: spacingY.md,
  },
  statRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: spacingY.sm,
  },
  statLabel: {
    fontFamily: FONTS.primary,
    fontSize: fontSizes.medium,
    color: colors.black_text,
  },
  statValue: {
    fontFamily: FONTS.primaryBold,
    fontSize: fontSizes.large,
    color: colors.black,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: spacingY.xs,
  },
  actionContainer: {
    marginTop: 0,
  },
  downloadButton: {
    paddingVertical: spacingY.md,
  },
});
